version: "3"
services:
    mongodb:
        restart: always
        container_name: mongodb
        image: mongo:4.4      
        environment:
            - MONGO_INITDB_DATABASE=TAD_Proyecto
        volumes:
            - ../data/mongo:/docker-entrypoint-initdb.d
        ports:
            - 27017:27017
        networks:
            static-net:
                ipv4_address: 192.168.0.2
    web-app-tad:
        restart: on-failure
        container_name: web-app-tad
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - "8080"
        ports:
            - 8080:8080
        networks:
            static-net:
                ipv4_address: 192.168.0.3
        environment:
            WAIT_HOSTS: mongo:27017
        depends_on:
            - mongodb
networks:
    static-net:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0/16